# Generated by Django 5.2 on 2025-04-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('processor', models.CharField(max_length=100, verbose_name='Procesador')),
                ('ram', models.CharField(max_length=50, verbose_name='RAM')),
                ('storage', models.CharField(max_length=100, verbose_name='Almacenamiento')),
                ('operating_system', models.CharField(max_length=100, verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Mini PC',
                'verbose_name_plural': 'Mini PCs',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('processor', models.CharField(max_length=100, verbose_name='Procesador')),
                ('ram', models.CharField(max_length=50, verbose_name='RAM')),
                ('storage', models.CharField(max_length=100, verbose_name='Almacenamiento')),
                ('operating_system', models.CharField(max_length=100, verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'PC',
                'verbose_name_plural': 'PCs',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('printer_type', models.CharField(max_length=50, verbose_name='Tipo de Impresora')),
                ('connection_type', models.CharField(max_length=50, verbose_name='Tipo de Conexión')),
                ('is_color', models.BooleanField(default=False, verbose_name='Es a Color')),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
            },
        ),
        migrations.CreateModel(
            name='PrinterMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Realizado por')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próxima Fecha de Mantenimiento')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='hardware.printer', verbose_name='Impresora')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Impresora',
                'verbose_name_plural': 'Mantenimientos de Impresoras',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
