# Generated by Django 5.2 on 2025-04-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipc',
            name='ip',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='pc',
            name='ip',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='printer',
            name='ip',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='IP'),
        ),
    ]
