# Generated by Django 5.2 on 2025-04-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_minipc_code_pc_code_printer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='printermaintenance',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20, verbose_name='Costo'),
        ),
    ]
