# Generated by Django 5.2 on 2025-04-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_printermaintenance_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printermaintenance',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Costo'),
        ),
    ]
