# Generated by Django 5.2 on 2025-04-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_alter_printermaintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='printermaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('limpieza', 'Limpieza'), ('cambio_toner', 'Cambio de Toner'), ('cambio_piezas', 'Cambio de piezas')], default='limpieza', max_length=20, verbose_name='Tipo de Mantenimiento'),
        ),
        migrations.CreateModel(
            name='InkStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ink_type', models.CharField(max_length=100, verbose_name='Tipo de Tinta')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Compra')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ink_stocks', to='hardware.printer', verbose_name='Impresora')),
            ],
            options={
                'verbose_name': 'Stock de Tinta',
                'verbose_name_plural': 'Stock de Tintas',
            },
        ),
    ]
