# Generated by Django 5.2 on 2025-04-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_printermaintenance_maintenance_type_inkstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inkstock',
            name='printer',
        ),
        migrations.AddField(
            model_name='inkstock',
            name='toner_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo de Toner'),
        ),
    ]
