# Generated by Django 5.2 on 2025-04-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_printermaintenance_toner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkstock',
            name='buying_price',
            field=models.IntegerField(default=0, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='printermaintenance',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Costo'),
        ),
    ]
