# Generated by Django 5.2.1 on 2025-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_alter_inkstock_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipc',
            name='codigo_red',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo Red'),
        ),
        migrations.AddField(
            model_name='pc',
            name='codigo_red',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo Red'),
        ),
        migrations.AddField(
            model_name='printer',
            name='codigo_red',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo Red'),
        ),
    ]
