# Generated by Django 5.2.1 on 2025-05-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_minipc_codigo_red_pc_codigo_red_printer_codigo_red'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minipc',
            name='codigo_red',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='codigo_red',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='codigo_red',
        ),
    ]
