# Generated by Django 5.2.1 on 2025-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_remove_minipc_codigo_red_remove_pc_codigo_red_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Cable')),
                ('source_device', models.CharField(help_text='Servidor o dispositivo de red de origen', max_length=100, verbose_name='Dispositivo de Origen')),
                ('destination_device', models.CharField(help_text='Máquina o dispositivo de destino', max_length=100, verbose_name='Dispositivo de Destino')),
                ('port_number', models.CharField(help_text='Puerto donde está conectado el cable', max_length=20, verbose_name='Número de Puerto')),
                ('cable_type', models.CharField(blank=True, help_text='Ej: Ethernet, Fibra óptica, etc.', max_length=50, verbose_name='Tipo de Cable')),
                ('cable_length', models.CharField(blank=True, max_length=20, verbose_name='Longitud del Cable')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cable de Red',
                'verbose_name_plural': 'Cables de Red',
                'ordering': ['cable_code'],
            },
        ),
    ]
